language: node_js

sudo: false

script:
  - npm test
  - npm run check-casing
  - nvm install stable
  - npm run lint
  - nvm use $TRAVIS_NODE_VERSION
  - npm run prepublish

node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "4.0"
  - "4.1"
  - "4"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5"
  - "6"
  - "7"
