language: node_js

dist: trusty
sudo: required

addons:
  chrome: stable

matrix:
  include:
    - node_js: "stable"
      env: COMMAND=preversion
    - node_js: "0.12"
      env: COMMAND=test
    - node_js: "4"
      env: COMMAND=test
    - node_js: "5"
      env: COMMAND=test
    - node_js: "6"
      env: COMMAND=test
    - node_js: "7"
      env: COMMAND=test
    - node_js: "8"
      env: COMMAND=test
    - node_js: "iojs"
      env: COMMAND=test

script:
  - npm run "$COMMAND"

addons:
  browserstack:
    username: "edgarhipp2"
    access_key:
      secure: "hKN6RhW6QlqEJ0elrkDbRCYP5IpN5MScN525BO2SU7xKjp6vpOm/HsERoelGjeGcBrrIv0mm+ugx3CObLWiijoA4MeQUIYViYnuS0QBKonKcrURUUMtOZcv4o2vAF3ew33Nzb00eS4qLI5dKPHGn5qh5YjqlrjVlQxsEQcYepek="
